user_agent: 'Mozilla/5.0 (compatible; gourmet/1.0 (https://gourmet-project.eu/)'
langs_of_interest: ['en','my']
crawl_delay: 5
max_time_per_site: 3600
connection_timeout: 10
max_jobs: 24
accepted_tlds: ['mm']
seed_urls_from_file: '/home/agaliano/wikidumps/mm_seed_urls.txt'
prefix_filter: ['mailto:']
output_dir: '/home/agaliano/mm_crawl_output'
verbose: True
accepted_content: '(text/html)'
max_folder_tree_depth: 20
max_attempts: 3
scout_steps: 200
min_langs_in_site: 2
mandatory_lang: 'my'
min_percent_mandatory_lang: 10
url_blacklist: ['wordpress','blogspot','facebook','google','wikipedia','youtube','perehodi','twitter','instagram']
